### ISSUE TITLE
Error when using Docker

### ISSUE THREAD

**Issue by michaelthreet** [microsoft/Samba#10]
Hello,

I have built a Docker image based on the Dockerfile provided, but I am seeing the following error when trying to prepare the data.

Docker command: `docker run -d --name samba -v ./data:/app/data -v /data/hf-cache:/data/hf-cache --runtime nvidia samba python scripts/prepare_slimpajama.py --source_path /data/hf-cache/datasets--cerebras--SlimPajama-627B/snapshots/2d0accdd58c5d5511943ca1f5ff0e3eb5e293543/ --tokenizer_path data/llama  --destination_path data/slim --split validation --percentage 1.0`

Container logs:

```

=============
== PyTorch ==
=============

NVIDIA Release 23.07 (build 63867923)
PyTorch Version 2.1.0a0+b5021ba

Container image Copyright (c) 2023, NVIDIA CORPORATION & AFFILIATES. All rights reserved.

Copyright (c) 2014-2023 Facebook Inc.
Copyright (c) 2011-2014 Idiap Research Institute (Ronan Collobert)
Copyright (c) 2012-2014 Deepmind Technologies    (Koray Kavukcuoglu)
Copyright (c) 2011-2012 NEC Laboratories America (Koray Kavukcuoglu)
Copyright (c) 2011-2013 NYU                      (Clement Farabet)
Copyright (c) 2006-2010 NEC Laboratories America (Ronan Collobert, Leon Bottou, Iain Melvin, Jason Weston)
Copyright (c) 2006      Idiap Research Institute (Samy Bengio)
Copyright (c) 2001-2004 Idiap Research Institute (Ronan Collobert, Samy Bengio, Johnny Mariethoz)
Copyright (c) 2015      Google Inc.
Copyright (c) 2015      Yangqing Jia
Copyright (c) 2013-2016 The Caffe contributors
All rights reserved.

Various files include modifications (c) NVIDIA CORPORATION & AFFILIATES.  All rights reserved.

This container image and its contents are governed by the NVIDIA Deep Learning Container License.
By pulling and using the container, you accept the terms and conditions of this license:
https://developer.nvidia.com/ngc/nvidia-deep-learning-container-license

NOTE: The SHMEM allocation limit is set to the default of 64MB.  This may be
   insufficient for PyTorch.  NVIDIA recommends the use of the following flags:
   docker run --gpus all --ipc=host --ulimit memlock=-1 --ulimit stack=67108864 ...

/usr/local/lib/python3.10/dist-packages/torchvision/io/image.py:13: UserWarning: Failed to load image Python extension: '/usr/local/lib/python3.10/dist-packages/torchvision/image.so: undefined symbol: _ZN3c1017RegisterOperatorsD1Ev'If you don't plan on using image functionality from `torchvision.io`, you can ignore this warning. Otherwise, there might be something wrong with your environment. Did you have `libjpeg` or `libpng` installed before building `torchvision` from source?
  warn(
Traceback (most recent call last):
  File "/app/scripts/prepare_slimpajama.py", line 21, in <module>
    import lit_gpt.packed_dataset as packed_dataset
  File "/app/lit_gpt/__init__.py", line 7, in <module>
    from lit_gpt.model import GPT
  File "/app/lit_gpt/model.py", line 15, in <module>
    from xformers.ops import SwiGLU
  File "/usr/local/lib/python3.10/dist-packages/xformers/ops/__init__.py", line 8, in <module>
    from .fmha import (
  File "/usr/local/lib/python3.10/dist-packages/xformers/ops/fmha/__init__.py", line 10, in <module>
    from . import (
  File "/usr/local/lib/python3.10/dist-packages/xformers/ops/fmha/triton_splitk.py", line 548, in <module>
    _get_splitk_kernel(num_groups)
  File "/usr/local/lib/python3.10/dist-packages/xformers/ops/fmha/triton_splitk.py", line 503, in _get_splitk_kernel
    _fwd_kernel_splitK_unrolled = unroll_varargs(_fwd_kernel_splitK, N=num_groups)
  File "/usr/local/lib/python3.10/dist-packages/xformers/triton/vararg_kernel.py", line 166, in unroll_varargs
    jitted_fn = triton.jit(fn)
  File "/usr/local/lib/python3.10/dist-packages/triton/runtime/jit.py", line 864, in jit
    return decorator(fn)
  File "/usr/local/lib/python3.10/dist-packages/triton/runtime/jit.py", line 853, in decorator
    return JITFunction(
  File "/usr/local/lib/python3.10/dist-packages/triton/runtime/jit.py", line 699, in __init__
    self.src = self.src[re.search(r"^def\s+\w+\s*\(", self.src, re.MULTILINE).start():]
AttributeError: 'NoneType' object has no attribute 'start'
```

**Comment by lulmer** [comment]
Facing the exact same error 
```shell
root@a6b1f5aa0ebd:/app# python scripts/prepare_slimpajama.py --source_path /data/datasets/SlimPajama-627B/ --tokenizer_path /data/checkpoints/llama-3-8b-instruct-hf/original/ --destination_path /data/datasets/slim --split validation --percentage 1.0 
/usr/local/lib/python3.10/dist-packages/torchvision/io/image.py:13: UserWarning: Failed to load image Python extension: '/usr/local/lib/python3.10/dist-packages/torchvision/image.so: undefined symbol: _ZN3c1017RegisterOperatorsD1Ev'If you don't plan on using image functionality from `torchvision.io`, you can ignore this warning. Otherwise, there might be something wrong with your environment. Did you have `libjpeg` or `libpng` installed before building `torchvision` from source?
  warn(
Traceback (most recent call last):
  File "/app/scripts/prepare_slimpajama.py", line 21, in <module>
    import lit_gpt.packed_dataset as packed_dataset
  File "/app/lit_gpt/__init__.py", line 7, in <module>
    from lit_gpt.model import GPT
  File "/app/lit_gpt/model.py", line 15, in <module>
    from xformers.ops import SwiGLU
  File "/usr/local/lib/python3.10/dist-packages/xformers/ops/__init__.py", line 8, in <module>
    from .fmha import (
  File "/usr/local/lib/python3.10/dist-packages/xformers/ops/fmha/__init__.py", line 10, in <module>
    from . import (
  File "/usr/local/lib/python3.10/dist-packages/xformers/ops/fmha/triton_splitk.py", line 548, in <module>
    _get_splitk_kernel(num_groups)
  File "/usr/local/lib/python3.10/dist-packages/xformers/ops/fmha/triton_splitk.py", line 503, in _get_splitk_kernel
    _fwd_kernel_splitK_unrolled = unroll_varargs(_fwd_kernel_splitK, N=num_groups)
  File "/usr/local/lib/python3.10/dist-packages/xformers/triton/vararg_kernel.py", line 166, in unroll_varargs
    jitted_fn = triton.jit(fn)
  File "/usr/local/lib/python3.10/dist-packages/triton/runtime/jit.py", line 864, in jit
    return decorator(fn)
  File "/usr/local/lib/python3.10/dist-packages/triton/runtime/jit.py", line 853, in decorator
    return JITFunction(
  File "/usr/local/lib/python3.10/dist-packages/triton/runtime/jit.py", line 699, in __init__
    self.src = self.src[re.search(r"^def\s+\w+\s*\(", self.src, re.MULTILINE).start():]
AttributeError: 'NoneType' object has no attribute 'start'
```

**Comment by renll** [comment]
Hmmm, I am not sure if the recent updates on nightly triton break anything unexpected, but I think you can try `pip install triton==2.2.0` to see if the problem persists.

**Comment by sriraman2020** [comment]
With Triton==2.2.0 below error is seen 


  warn(
Traceback (most recent call last):
  File "/workspace/scripts/prepare_slimpajama.py", line 21, in <module>
    import lit_gpt.packed_dataset as packed_dataset
  File "/workspace/lit_gpt/__init__.py", line 7, in <module>
    from lit_gpt.model import GPT
  File "/workspace/lit_gpt/model.py", line 18, in <module>
    from .mamba_simple import Mamba
  File "/workspace/lit_gpt/mamba_simple.py", line 12, in <module>
    from mamba_ssm.ops.selective_scan_interface import selective_scan_fn, mamba_inner_fn
  File "/usr/local/lib/python3.10/dist-packages/mamba_ssm/__init__.py", line 3, in <module>
    from mamba_ssm.ops.selective_scan_interface import selective_scan_fn, mamba_inner_fn
  File "/usr/local/lib/python3.10/dist-packages/mamba_ssm/ops/selective_scan_interface.py", line 16, in <module>
    import selective_scan_cuda
ImportError: /usr/local/lib/python3.10/dist-packages/selective_scan_cuda.cpython-310-x86_64-linux-gnu.so: undefined symbol: _ZN3c104cuda9SetDeviceEi

**Comment by renll** [comment]
Let's try Triton==2.3.1 then lol

**Comment by lulmer** [comment]
> Let's try Triton==2.3.1, the latest stable release then lol.

Just tried, and had an error about the selective_scan... Seems like mamba_ssm does not like triton 2.3.1 as it keeps reinstalling the 2.3.0 whilst reinstalling it too.

**Comment by renll** [comment]
Closed as the dockerfile is updated. If met the problems related to transformer engine library, please try `sudo pip uninstall -y transformer-engine`
